# AI Code Audit System Configuration
# This file contains the main configuration for the AI Code Audit System

# Database Configuration
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "jackhou."
  database: "ai_code_audit_system"
  charset: "utf8mb4"
  pool_size: 10
  max_overflow: 20

# LLM (Large Language Model) Configuration
llm:
  default_model: "kimi-k2"

  # Kimi Provider (SiliconFlow) - 默认首选
  kimi:
    api_key: "sk-kpepqjjtmxpcdhqcvrdekuroxvmpmphkfouhzbcbudbpzzzt"
    base_url: "https://api.siliconflow.cn/v1"
    model_name: "moonshotai/Kimi-K2-Instruct"
    enabled: true
    priority: 1
    max_requests_per_minute: 30
    cost_weight: 1.0
    performance_weight: 1.0
    timeout: 30

  # Qwen Provider (SiliconFlow) - 备用选择
  qwen:
    api_key: "sk-bldkmthquuuypfythtasqvdhwtclplekygnbylvboctetkeh"
    base_url: "https://api.siliconflow.cn/v1"
    model_name: "Qwen/Qwen3-Coder-30B-A3B-Instruct"
    enabled: true
    priority: 2
    max_requests_per_minute: 60
    cost_weight: 1.2
    performance_weight: 1.1
    timeout: 60

# Audit Configuration
audit:
  max_concurrent_sessions: 3
  cache_ttl: 86400  # 24 hours in seconds
  max_file_size: 100000  # 100KB
  max_files_per_audit: 50
  
  supported_languages:
    - "python"
    - "javascript"
    - "typescript"
    - "java"
    - "go"
    - "rust"
    - "cpp"
    - "c"
    - "csharp"
    - "php"
    - "ruby"
    - "kotlin"
    - "swift"
    - "scala"
  
  output_formats:
    - "json"
    - "yaml"
    - "table"
    - "markdown"
    - "html"

# Security Rules Configuration
security_rules:
  sql_injection: true
  xss: true
  csrf: true
  authentication: true
  authorization: true
  data_validation: true
  sensitive_data_exposure: true
  insecure_crypto: true
  code_injection: true
  path_traversal: true

# Application Settings
cache_dir: "./cache"
log_level: "INFO"
debug: false

# Advanced Settings
advanced:
  # Enable experimental features
  experimental_features: false
  
  # Performance tuning
  performance:
    max_parallel_requests: 5
    request_timeout: 120
    retry_attempts: 3
    retry_delay: 2
  
  # Analysis settings
  analysis:
    deep_analysis: true
    include_dependencies: true
    analyze_test_files: false
    max_context_length: 32768
  
  # Report settings
  reports:
    include_code_snippets: true
    max_snippet_length: 500
    include_fix_suggestions: true
    severity_threshold: "medium"

    # Default report generation settings
    auto_generate_reports: true
    default_formats: ["json", "markdown"]
    default_output_dir: "./reports"
    filename_template: "audit_report_{timestamp}_{project_name}"
    default_template: "security_audit_chinese"

# File filtering configuration
file_filtering:
  enabled: true

  # Absolute ignore patterns (no security risk)
  ignore_patterns:
    # Dependencies and packages
    - "node_modules/**"
    - "vendor/**"
    - "venv/**"
    - ".venv/**"
    - "__pycache__/**"
    - "site-packages/**"
    - "target/**"
    - ".m2/**"
    - "lib/**"

    # Build outputs
    - "dist/**"
    - "build/**"
    - ".next/**"
    - ".nuxt/**"
    - "out/**"
    - "public/build/**"

    # Minified and bundled files
    - "*.min.js"
    - "*.bundle.js"
    - "*.chunk.js"
    - "*.min.css"

    # Static assets
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.gif"
    - "*.svg"
    - "*.ico"
    - "*.woff"
    - "*.woff2"
    - "*.ttf"
    - "*.eot"
    - "*.mp4"
    - "*.mp3"
    - "*.wav"
    - "*.pdf"

    # Version control and IDE
    - ".git/**"
    - ".svn/**"
    - ".hg/**"
    - ".vscode/**"
    - ".idea/**"
    - "*.iml"
    - ".DS_Store"

  # Conditional ignore (can be controlled by parameters)
  conditional_ignore:
    css_files: true          # Ignore CSS files
    test_files: true         # Ignore test files
    doc_files: false         # Don't ignore documentation files
    log_files: true          # Ignore log files

  # File size limits
  max_file_size: 512000      # 500KB in bytes

  # Force include patterns (audit even if matches ignore rules)
  force_include:
    - "*.env*"
    - "*.config.*"
    - "*.conf"
    - "*.ini"
    - "*.secret*"
    - "*.key"
    - "*.pem"
    - "*.crt"

  # Smart detection settings
  detect_libraries: true     # Auto-detect library files
  use_gitignore: true        # Use .gitignore rules

  # Test file patterns
  test_patterns:
    - "*test.*"
    - "*spec.*"
    - "test/**"
    - "tests/**"
    - "__tests__/**"
    - "spec/**"

  # CSS file patterns
  css_patterns:
    - "*.css"
    - "*.scss"
    - "*.sass"
    - "*.less"
    - "*.styl"

  # Documentation patterns
  doc_patterns:
    - "*.md"
    - "*.txt"
    - "*.rst"
    - "*.adoc"
    - "docs/**"
    - "documentation/**"

  # Log file patterns
  log_patterns:
    - "*.log"
    - "logs/**"
    - "log/**"

  # Library detection keywords
  library_keywords:
    - "jQuery"
    - "Bootstrap"
    - "Lodash"
    - "React"
    - "Vue"
    - "Angular"
    - "Generated by"
    - "Auto-generated"
    - "This file is automatically generated"
    - "Do not edit this file"
